name: coin_gecko
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  dio: ^5.7.0
  shimmer: ^3.0.0
  mrx_charts: ^0.1.3
  intl: ^0.18.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

